### PR TITLE
first draft of solution to selaltloc bug

### LINKED ISSUE #153: pdb_selaltloc removes residues with (only) alternate locations
**Describe the bug**
pdb_selaltloc removes residues in which all atoms show alternate locations

**To Reproduce**
```
grep -rn pdb4xoj.pdb -e "SER A  85"
pdb_selaltloc pdb4xoj.pdb > pdb4xoj-occ.pdb
grep -rn pdb4xoj-occ.pdb -e "SER A  85"
```

**Expected behavior**
`pdb_selaltloc` should not delete the residue but rather pick one of the two available alternate locations

**Desktop (please complete the following information):**
 - OS: Linux
 - Python Version 3.9
 
[pdb4xoj.pdb.zip](https://github.com/haddocking/pdb-tools/files/10165819/pdb4xoj.pdb.zip)

### PR DESCRIPTION
**Pull request by mgiulini**
Closes #153 by adding an if-clause on the ' ' key in `flush_resloc_occ` function.

### CODE REVIEW

**Comment by mgiulini** [comment]
Two tests do not pass, namely:
```
pdb_selaltloc data/dummy_altloc.pdb
pdb_selaltloc data/dummy_altloc2.pdb
```
@joaomcteixeira could you please check them?

according to the old implementation the residue ILE 25 should be excluded, but in my opinion that's wrong.

Please check this PR carefully, as I didn't fully understand the quite complicated logic of the algorithm.

**Comment by joaomcteixeira** [comment]
Thanks Marco,

Sorry to ask, but could you please add the test cases for the example we are trying to solve, along with some testing PDBs? Otherwise will be very difficult to review and test the code. `pdb-tools` is one of those projects we really need to go along with test-driven development; otherwise, we are lost because there are so many cases.

I will look into the detail of those tests you referred to, but those have been so inspected in the past, yet a bug could have gone along.

Cheers,

**Comment by mgiulini** [comment]
hi Joao, a reference case is already present in #153, I copied part of that file in the tests/data folder and implemented a new test.

Cheers,
Marco

**Comment by joaomcteixeira** [comment]
Thanks, I will look at it asap.

**Comment by mgiulini** [comment]
hi @joaomcteixeira , do you have updates on this?

**Comment by joaomcteixeira** [comment]
Not yet, sorry. Will try doing it asap.

**Comment by joaomcteixeira** [comment]
Closing in favor of #156

**Pull request closed without merging**
