### PR TITLE
Considers isalhum in pdb_selchain

### PR DESCRIPTION
**Pull request by joaomcteixeira**
Considers chain options to be valid when str.isalnum() is True.

Solves #39

### CODE REVIEW

**Comment by mtrellet** [comment]
Works fine on my side! Thanks ;)

**Comment by JoaoRodrigues** [comment]
Seems good for me. Mind adding a test to check this? (A small example with 3 chains, A, a, and B where we select each would work).

**Comment by joaomcteixeira** [comment]
Added tests for selecting capital chain identifiers, lowercase identifiers and digit identifiers.

@JoaoRodrigues review and merge if appropriate.

**Comment by JoaoRodrigues** [comment]
Seems good! Thanks for the fix and the tests!

**Pull request merged**
