### PR TITLE
Tool to convert between atom names conventions

### PR DESCRIPTION
**Pull request by joaomcteixeira**
Follows discussion on #113 

For now, adds two conversion tables between:

- BMRB/PDBv3/Amber
- Old PDB

The input `pdb` atom name format is guessed on the fly, hence there is a bit of computation penalty.

**TODO:**
- ~~implement XPLOR~~
- tests
- improve docs
- ~~N-terminal Hs, also PRO~~
- ~~histidines~~
- make trick to implement `OT1` like atoms.

What are your thoughts?

Still, I think #113 is a valuable tool.

### CODE REVIEW

**Review by amjjbonvin — APPROVED** [review]
Looks good to me. Did not check though against the HADDOCK topologies. The file containing all amino acids topologies in HADDOCK is in the `toppar` directory and called: `protein-allhdg5-4.top`

**Comment by joaomcteixeira** [comment]
I am checking and they are the same as `xplor`. One difference is that `xplor` (according to here) has HB2/HB1 swapped with 1HB/2HB with the other nomenclatures. Did you know anything about this for `CNS`?

Another important change is: 

`! CNS v1.3 (27-Feb-10): changed OT1, OT2 to O, OXT, respectively`. `xplor` keeps `OT1` and `OT2`.

**Comment by joaomcteixeira** [comment]
I think this is it. tests okay in py27 and py38. @JoaoRodrigues have your say.

**Comment by joaomcteixeira** [comment]
A user from the forum is requesting this tool -> https://ask.bioexcel.eu/t/prodigy-fails-to-calculate-binding-energy-of-protein-protein-complex/3420/3

I think is it's a useful tool and we should merge it soon.

**Review by rvhonorato — APPROVED** [review]

**Comment by JoaoRodrigues** [comment]
I'm gonna go ahead and close this since we discussed online that this falls a little out of the scope of the tools and requires a lot of maintenance (all the conversion schemes, etc need to be maintained).

**Pull request closed without merging**
