### PR TITLE
Added new tool pdb_uniq

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
Addresses issue #12. I opted by creating a new tool instead of changing `pdb_wc`. It lists unique residue names and chain identifiers, which I consider to be the most commonly sought things? It keeps the order in which things were found (instead of alphabetical or so).

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
I thought of that but you can always do `pdb_selhetatm file.pdb | pdb_uniq`. Would it work?

**Comment by amjjbonvin** [comment]
I guess it would do the job, but personally I don't see when I would use such a `pdb_uniq` tool. 
Having first to select the HETATM and then use `pdb_uniq` seems cumbersome. I would rather like to know what is in a file without having to first select parts.

`pdb_wc` already tells you the number of chains and if there is an HETATM or not.  Knowing the chainIDs and the ligand resname is all I would be interested in. Which amino acids are presents seems rather irrelevant. 

But that's only my view of it of course

**Comment by mtrellet** [comment]
Could not we have a third option/line output with heteroatoms? Putting everything under "Residues" could be slightly misleading and the distinction would greatly improve the readability in my opinion.

**Comment by JoaoRodrigues** [comment]
I see that's a wanted feature :) I'll change it!

**Comment by JoaoRodrigues** [comment]
Added a `-h` flag to show HETATM residue names.

**Comment by JoaoRodrigues** [comment]
Superseeded by #51

**Pull request closed without merging**
