### PR TITLE
Adds for loop example to docs

### PR DESCRIPTION
**Pull request by joaomcteixeira**
Every time I use `pdb-tools` I always feel it is an amazing tool. :heart_eyes:  I believe extra examples can help the users understand the capabilities of the `pdb-tools` design. 

This PR adds a little, yet powerful, example with bash `for` loop.

### CODE REVIEW

**Review by amjjbonvin — APPROVED** [review]
Nice - the more examples the better!

**Review by JoaoRodrigues — APPROVED** [review]

**Comment by JoaoRodrigues** [comment]
Following this example, we could have a cookbook with "recipes" for combining the tools. That could help newcomers get started?

**Comment by joaomcteixeira** [comment]
I agree, @JoaoRodrigues 
Actually, the submitted example is a tentative to seed that.
Shall all those examples go to the current section or should there be a specific section of combination examples? Wherever it should go, once we decide on that, we can simply continue PR examples as we use them in our daily work.

**Comment by JoaoRodrigues** [comment]
We can add a `COOKBOOK.md` or an `EXAMPLES.md` file that simply lists examples in list. We'd have to link it to the `index.md` file so that it shows up in the web page and include this one in a `setup.cfg` file so that it is shipped with the code.

**Comment by joaomcteixeira** [comment]
Cookbook added in #97

**Pull request merged**
