### PR TITLE
Added tool to select HETATM records. 

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
Suggested by @cgott98 in issue #19. Extracts HETATM records from the file.

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
I would leave that to `pdb_tidy`. I find it easier like this, specially if you want to merge/split later on. What do you think?

**Comment by amjjbonvin** [comment]
Fine as long as all selection tools have the same behaviour, which doesn't seem to be the case. E.g. `pdb_selchain` does keep the TER and END statements.

**Comment by JoaoRodrigues** [comment]
Will have a look and standardize the behavior!

**Comment by JoaoRodrigues** [comment]
Had a look. The reason why `pdb_selchain` keeps `TER` statements is because there is actually some chain information in there. For instance, `pdb_selseg` cannot pick `TER` statements reliably (they don't have a segment id) so it skips them. For `HETATM`, this is very inconsistent because some ligands are at the end of the PDB file while others (e.g. MSE) are mixed with the regular sequence. Getting proper TER records from this would be a mess... so I vote to leave it as is and rely on `pdb_tidy` to then add the proper statements.

**Comment by amjjbonvin** [comment]
Ok - fine on my side. By the way, another useful feature/tool would be to replace MSE simply by MET and change to ATOM instead of HETATM. Leaving it as HETATM and applying `pdb_tidy` will had every time TER statements around it, causing some software not to create peptidic bonds for those.

**Comment by JoaoRodrigues** [comment]
I'll make a new issue for that one. I have an idea on how to work that out, but it'd include removing atoms that are _not_ in the standard residue.

**Pull request merged**
